apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-policy"
spec:
  targets:
  - name: "services-ingressgateway"
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "http://jwt.authenticator.svc.cluster.local:8000/jwks.json"
  principalBinding: USE_ORIGIN
